name: weather_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.2.0
  geolocator: ^11.0.0
  flutter_spinkit: ^5.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
     - assets/background.png
     - assets/house.png
     - assets/bg.png
     - assets/weatherTemperatureCold.png
     - assets/weatherTemperatureHot.png
     - assets/weatherTemperatureWarm.png
     - assets/weatherAtmosphericPressure.png
     - assets/ic_wind_speed.png
     - assets/ic_temp.png
     - assets/ic_humidity.png


  fonts:
     - family: SFPRO
       fonts:
         - asset: fonts/SFPRODISPLAYREGULAR.OTF


